dubbo:
  application:
    name: provider
  registry:
    address: nacos://127.0.0.1:8848
  #    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: xyz.qiuyiping.nacosdubbo.provider
